/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmaciaalfa;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 *
 * @author lukas
 */
public class LoginCliente extends javax.swing.JDialog {

    public static String nomec;
    public static String datac;
    public static String cpfc;
    public static String sexoc;
    public static String celular1c;
    public static String celular2c;
    public static String emailc;
    public static String loginc;
    public static String senhac;
    
    public LoginCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtlogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        entrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Farmacia Alpha");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton1)
                .addGap(90, 90, 90)
                .addComponent(entrar)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(20, 20, 20)))
                    .addContainerGap(102, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(entrar))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel3)
                    .addGap(43, 43, 43)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadastrocliente cc = new cadastrocliente(null, true);
        cc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // Caminho do arquivo onde os dados dos usuários estão salvos
        Path path = Path.of("dados_cliente.txt");

        // Obtém o nome de usuário e a senha digitados no login
        String usuarioDigitado = txtlogin.getText();
        String senhaDigitada = new String(txtsenha.getPassword());  // Converte a senha para String

        try {
            // Verifica se o arquivo existe
            if (Files.exists(path)) {
                // Lê o conteúdo do arquivo
                String conteudoArquivo = Files.readString(path, java.nio.charset.StandardCharsets.UTF_8);

                // Divide o conteúdo do arquivo em partes, considerando que cada cadastro de usuário
                // é separado por quebras de linha.
                String[] usuarios = conteudoArquivo.split("\n\n");  // Considera que cada cadastro tem uma linha em branco entre eles

                // Variáveis para verificar se o usuário existe e se a senha está correta
                boolean usuarioEncontrado = false;
                boolean senhaCorreta = false;

                if (usuarioDigitado.isBlank() && usuarioDigitado.isEmpty()) {

                }else{
                    // Percorre todos os registros de usuários
                    for (String usuarioInfo : usuarios) {
                        // Verifica se o cadastro contém o usuário digitado
                        if (usuarioInfo.contains("Usuário: " + usuarioDigitado)) {
                            usuarioEncontrado = true;

                            if (senhaDigitada.isBlank() && senhaDigitada.isEmpty()) {

                            }else{
                                // Se encontrou o usuário, verifica a senha
                                if (usuarioInfo.contains("Senha: " + senhaDigitada)) {
                                    senhaCorreta = true;

                                    // Agora, vamos capturar as outras informações do usuário
                                    // Divida o texto do registro do usuário em linhas
                                    String[] linhas = usuarioInfo.split("\n");

                                    // Atribuindo as outras informações às variáveis correspondentes
                                    for (String linha : linhas) {
                                        if (linha.startsWith("Nome: ")) {
                                            nomec = linha.replace("Nome: ", "").trim();
                                        } else if (linha.startsWith("Data de Nascimento: ")) {
                                            datac = linha.replace("Data de Nascimento: ", "").trim();
                                        } else if (linha.startsWith("CPF: ")) {
                                            cpfc = linha.replace("CPF: ", "").trim();
                                        } else if (linha.startsWith("Sexo: ")) {
                                            sexoc = linha.replace("Sexo: ", "").trim();
                                        } else if (linha.startsWith("Celular 1: ")) {
                                            celular1c = linha.replace("Celular 1: ", "").trim();
                                        } else if (linha.startsWith("Celular 2: ")) {
                                            celular2c = linha.replace("Celular 2: ", "").trim();
                                        } else if (linha.startsWith("E-mail: ")) {
                                            emailc = linha.replace("E-mail: ", "").trim();
                                        }
                                    }

                                    break;  // Não precisa continuar buscando, pois já encontramos o usuário e validamos a senha
                                }
                            }
                        }
                    }
                }

                // Se o usuário foi encontrado e a senha estiver correta
                if (usuarioEncontrado && senhaCorreta) {
                    // Mensagem de sucesso
                    javax.swing.JOptionPane.showMessageDialog(this, "Login bem-sucedido!");
                    this.dispose();
                } else if (usuarioEncontrado) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Senha incorreta!");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Arquivo de dados não encontrado!");
            }
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao acessar os dados: " + e.getMessage());
        }
    }//GEN-LAST:event_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginCliente dialog = new LoginCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
