/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lukas
 */
public class telalogin extends javax.swing.JDialog {

    public static String nome;
    public static String email;
    public static String cpf;
    public static String sexo;
    public static String login;
    public static String senha;
    public static String data;
    public static String celular1;
    public static String celular2;
    
    public telalogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        entrar8 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jLabel25.setText("Usuário");

        jLabel26.setText("Senha");

        entrar8.setText("Entrar");
        entrar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar8ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel27.setText("Farmacia Alpha");

        jButton9.setText("Cadastrar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel26)
                        .addComponent(jLabel25)
                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(90, 90, 90)
                        .addComponent(entrar8))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(43, 43, 43)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(entrar8))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar8ActionPerformed
        // Caminho do arquivo onde os dados dos usuários estão salvos
        Path path = Path.of("dados_usuario.txt");

        // Obtém o nome de usuário e a senha digitados no login
        String usuarioDigitado = jTextField1.getText();
        String senhaDigitada = new String(jPasswordField1.getPassword());  // Converte a senha para String

        try {
            // Verifica se o arquivo existe
            if (Files.exists(path)) {
                // Lê o conteúdo do arquivo
                String conteudoArquivo = Files.readString(path, java.nio.charset.StandardCharsets.UTF_8);

                // Divide o conteúdo do arquivo em partes, considerando que cada cadastro de usuário
                // é separado por quebras de linha.
                String[] usuarios = conteudoArquivo.split("\n\n");  // Considera que cada cadastro tem uma linha em branco entre eles

                // Variáveis para verificar se o usuário existe e se a senha está correta
                boolean usuarioEncontrado = false;
                boolean senhaCorreta = false;

                if (usuarioDigitado.isBlank() && usuarioDigitado.isEmpty()) {

                }else{
                    // Percorre todos os registros de usuários
                    for (String usuarioInfo : usuarios) {
                        // Verifica se o cadastro contém o usuário digitado
                        if (usuarioInfo.contains("Usuário: " + usuarioDigitado)) {
                            usuarioEncontrado = true;

                            if (senhaDigitada.isBlank() && senhaDigitada.isEmpty()) {

                            }else{
                                // Se encontrou o usuário, verifica a senha
                                if (usuarioInfo.contains("Senha: " + senhaDigitada)) {
                                    senhaCorreta = true;

                                    // Agora, vamos capturar as outras informações do usuário
                                    // Divida o texto do registro do usuário em linhas
                                    String[] linhas = usuarioInfo.split("\n");

                                    // Atribuindo as outras informações às variáveis correspondentes
                                    for (String linha : linhas) {
                                        if (linha.startsWith("Nome: ")) {
                                            nome = linha.replace("Nome: ", "").trim();
                                        } else if (linha.startsWith("Data de Nascimento: ")) {
                                            data = linha.replace("Data de Nascimento: ", "").trim();
                                        } else if (linha.startsWith("CPF: ")) {
                                            cpf = linha.replace("CPF: ", "").trim();
                                        } else if (linha.startsWith("Sexo: ")) {
                                            sexo = linha.replace("Sexo: ", "").trim();
                                        } else if (linha.startsWith("Celular 1: ")) {
                                            celular1 = linha.replace("Celular 1: ", "").trim();
                                        } else if (linha.startsWith("Celular 2: ")) {
                                            celular2 = linha.replace("Celular 2: ", "").trim();
                                        } else if (linha.startsWith("E-mail: ")) {
                                            email = linha.replace("E-mail: ", "").trim();
                                        }
                                    }

                                    break;  // Não precisa continuar buscando, pois já encontramos o usuário e validamos a senha
                                }
                            }
                        }
                    }
                }

                // Se o usuário foi encontrado e a senha estiver correta
                if (usuarioEncontrado && senhaCorreta) {
                    // Mensagem de sucesso
                    javax.swing.JOptionPane.showMessageDialog(this, "Login bem-sucedido!");
                    this.dispose();
                } else if (usuarioEncontrado) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Senha incorreta!");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Arquivo de dados não encontrado!");
            }
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao acessar os dados: " + e.getMessage());
        }
    }//GEN-LAST:event_entrar8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        TelaCadastrar1 tc = new TelaCadastrar1(null, true);
        tc.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                telalogin dialog = new telalogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JButton entrar1;
    private javax.swing.JButton entrar2;
    private javax.swing.JButton entrar3;
    private javax.swing.JButton entrar4;
    private javax.swing.JButton entrar5;
    private javax.swing.JButton entrar6;
    private javax.swing.JButton entrar7;
    private javax.swing.JButton entrar8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtlogin1;
    private javax.swing.JTextField txtlogin2;
    private javax.swing.JTextField txtlogin3;
    private javax.swing.JTextField txtlogin4;
    private javax.swing.JTextField txtlogin5;
    private javax.swing.JTextField txtlogin6;
    private javax.swing.JTextField txtlogin7;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JPasswordField txtsenha1;
    private javax.swing.JPasswordField txtsenha2;
    private javax.swing.JPasswordField txtsenha3;
    private javax.swing.JPasswordField txtsenha4;
    private javax.swing.JPasswordField txtsenha5;
    private javax.swing.JPasswordField txtsenha6;
    private javax.swing.JPasswordField txtsenha7;
    // End of variables declaration//GEN-END:variables
}
